language: clojure
lein: lein
before_script: lein with-profile dev javac
script: lein all test
branches:
  only:
    - master
    - 1.2.x-stable
    - 1.1.x-stable
    - 1.0.x-stable
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
services:
  - riak
